### ISSUE TITLE
matching by specific covariates (age, sex) in MatchIt

### ISSUE THREAD

**Issue by MoniqueStenzel** [ngreifer/MatchIt#2]
In the MatchIt documentation I can't find any information  on how to do matching by specific covariates (e.g. age, sex). I.e. I don't want to do propensity score matching, but I want to match patients by age (e.g. 70yr old treated with 70yr old controls or even with a range like +- 2 years) and sex (e.g. male treated are matched with male controls). 
Is there this possibility in MatchIt?

**Comment by ngreifer** [comment]
It sounds like you want nearest neighbor matching with a caliper on age and an exact matching constraint on sex. For example, you could do the following:
```
matchit(treat ~ age + sex, data = data, exact = ~sex, caliper = c(age = 2), std. caliper = FALSE)
```
This does estimate a propensity score, but you can prevent this by setting `distance = "mahalanobis"`, which will ensure pairs are close on age and any other variables you might include in the formula but not in the `exact` argument.

**Comment by MoniqueStenzel** [comment]
Thanks very much! This helps a lot, my problem is solved.
