### ISSUE TITLE
Using a case as a control until the event occurs in the observation period (risk set sampling)

### ISSUE THREAD

**Issue by MoniqueStenzel** [ngreifer/MatchIt#3]
In the matchit package, you define a two-sided formula() object that contains the treatment and covariates used for creating the distance measure used in matching. The treatment variable is binary in this context. 

However, how can I specify it if I want to use a case also as a control until the event occurs in the observation period (cf. fig.1 c risk set sampling)?

![image](https://user-images.githubusercontent.com/109208194/211748210-3798247c-64c4-44fc-b32c-b861e8ec53f7.png)
Iwagami et al. (2022): Introduction to Matching in Case-Control and Cohort Studies. Annals of Clinical Epidemiology (https://www.researchgate.net/journal/Annals-of-Clinical-Epidemiology-2434-4338) 4(2):33-40
DOI:[10.37737/ace.22005](http://dx.doi.org/10.37737/ace.22005) 

I do not mean the option "with replacement / without replacement", because "with replacement" means a control used several times as a control, but does not itself become a case in the observation period.

**Comment by ngreifer** [comment]
Sorry for the late reply on this. This seems beyond what `MatchIt` can do. It was designed for simpler situations in which treatment assignment is determined at a single time point.

**Comment by MoniqueStenzel** [comment]
Thank you for your reply. I was afraid of that, but wanted to make sure I hadn't overlooked anything.
In the context of (medical) case-control studies, person-time-based approaches to control selection (incidence density sampling, risk set sampling, case-cohort sampling) are indispensable. Is the add-on of person-time based matching for the MatchIt package planned or would this implementation be possible?
